### ISSUE TITLE
Decide workflow

### ISSUE THREAD

**Issue by sachamorgese** [sachamorgese/unnamed-project#4]
What tools should we use? How should we proceed? Who's taking care of what? What do we want to learn? Let's discuss here

**Comment by kevoneil** [comment]
Yo

**Comment by sachamorgese** [comment]
I'd like to go with **agile/scrum** for this project:

1) It allows us to work independently.
2) It's an industry standard (in countries where people know what they're doing).

Since this is a side-project, we need some extra flexibility. All of the deadlines are going to be guidelines, nothing more than that. However, some issues have a higher priority and being unable to complete them in the appropriate time might slow down the others. Other people can take over, but **we need to have good communication**.

I'd like to go with 6 phases. First 2 phases code = false. Last 4, code = true.

**Brainstorming** < --- We talk and come up with ideas, decide MVP, Stack, and Workflow. NOW
- Ideally 1 week.

**Planning/Design** < --- We expand on the previous phase, start writing documentation and create issues. UI, UX, API, testing etc.
- Ideally 1 or 2 weeks

**Set Up** (could be seen as Sprint 1?) < --- We set up everything we need to deliver the MVP. This includes all dependencies, wiring up React/Redux/Whatever we're going to use. Write unit testings here.
- Ideally 1 week

**Sprints** < --- We get into full coding, I propose 1-week sprints. Write unit testings here. Some integration testing as well, if possible.

**Testing** < --- We try to break the app and then fix it. Integration testing.
- Probably around 2 weeks.

**Release** < --- Sell out, bro down!

What do you think?

**Comment by TheOmegaBlack** [comment]
Test

**Comment by sachamorgese** [comment]
This issue was moved to Techkyo/tech-kyo-blog#4
