### ISSUE TITLE
Blog-articles

### ISSUE THREAD

**Issue by sachamorgese** [sachamorgese/unnamed-project#9]
What articles should be in the blog when it launches?

**Comment by sachamorgese** [comment]
### Individual
**About us page**:
- Name, age, hobbies, picture

**Background**: 
An article that answers the question: Why did I come to Japan, how did I get my first engineering gig, what do I like/dislike about working in Japan?

### Generic
- What's this blog about? What are we trying to accomplish?
- How does one come to Japan and work
- Work culture
- Differences between working In Japan and working abroad

**Comment by anfusion** [comment]
What is the job market like for developers, especially foreigners, and what languages are in most demand

**Comment by sachamorgese** [comment]
This issue was moved to Techkyo/tech-kyo-blog#1
